name: 'Build NSO-RPC'
on:
  release:
    types: [released]

jobs:
  build:
    name: 'Build NSO-RPC'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    # Windows Build 
    - name: "Build"
      if: matrix.os == 'windows-latest'
      run: cd scripts && ./build.bat
    
    - name: "Upload Build"
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: client/dist/NSO-RPC.exe

    # Linux Build
    - name: "Copy install.sh to linux.sh"
      if: matrix.os == 'ubuntu-latest'
      run: cp scripts/install.sh scripts/linux.sh

    - name: "Upload script"
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: scripts/linux.sh


    # MacOS Build
    - name: "Build"
      if: matrix.os == 'macos-latest'
      run: |
        cd scripts &&
        ./build.sh &&
        cd ../client/dist &&
        zip -yr mac-portable.zip NSO-RPC.app/ &&
        productbuild --component NSO-RPC.app /Applications NSO-RPC.pkg &&
        zip -yr mac-installer.zip NSO-RPC.pkg

    - name: "Upload Build"
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/mac-installer.zip
          client/dist/mac-portable.zip
