name: 'Build NSO-RPC - x86_64'
on:
  release:
    types: [published]

jobs:
  build-x86_64:
    name: 'Build NSO-RPC - x86_64'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        pyqt_version: ['pyqt6', 'pyqt5']  # Reversed order to ensure PyQt6 is built first
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.11.4

    # Windows Build
    - name: "Set executable filename"
      if: matrix.os == 'windows-latest'
      run: |
        if [ "${{ matrix.pyqt_version }}" = "pyqt6" ]; then
          export EXECUTABLE_NAME="NSO-RPC.exe"
        elif [ "${{ matrix.pyqt_version }}" = "pyqt5" ]; then
          export EXECUTABLE_NAME="NSO-RPC-qt5.exe"
        fi
    - name: "Build"
      if: matrix.os == 'windows-latest'
      run: |
        cd scripts &&
        python -m pip install ${{ matrix.pyqt_version }} &&
        ./build.bat
    - name: "Rename executable"
      if: matrix.os == 'windows-latest' && matrix.pyqt_version == 'pyqt5'
      run: |
        mv client/dist/NSO-RPC.exe client/dist/NSO-RPC-qt5.exe

    - name: "Upload Build"
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/${{ env.EXECUTABLE_NAME }}

    # Linux Build
    - name: "Upload script"
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: scripts/linux.sh

    # MacOS Build
    - name: "Build"
      if: matrix.os == 'macos-latest'
      run: |
        cd scripts &&
        python -m pip install pyqt6 &&
        bash ./build.sh &&
        cd ../client/dist &&
        ln -s /Applications "Applications (admin)" &&
        hdiutil create -fs HFS+ -srcfolder . -volname NSO-RPC mac-installer.dmg &&
        zip -yr mac-portable.zip NSO-RPC.app/

    - name: "Upload Build"
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/mac-installer.dmg
          client/dist/mac-portable.zip

  build-universal2:
    name: 'Build NSO-RPC - Universal2'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    # MacOS Universal Build
    - name: "Install Python 3.11.4 and build NSO-RPC"
      run: |
        curl https://www.python.org/ftp/python/3.11.4/python-3.11.4-macos11.pkg -o python-3.11.4-macos11.pkg
        sudo installer -verbose -pkg python-3.11.4-macos11.pkg -target / &&
        alias python3=python3.11
        cd scripts/macos-universal2 &&
        bash ./build.sh &&
        cd ../../client/dist &&
        ln -s /Applications "Applications (admin)" &&
        hdiutil create -fs HFS+ -srcfolder . -volname NSO-RPC mac-universal2-installer.dmg &&
        zip -yr mac-universal2-portable.zip NSO-RPC.app/

    - name: "Upload NSO-RPC Universal2 Build"
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/mac-universal2-installer.dmg
          client/dist/mac-universal2-portable.zip

  get-hashes:
    runs-on: "ubuntu-latest"
    needs: ["build-x86_64", "build-universal2"]
    steps:
      - name: "Generate checksums.txt"
        uses: MCJack123/ghaction-generate-release-hashes@v4
        with:
          hash-type: sha256
          file-name: checksums.txt
          get-assets: true
      - uses: softprops/action-gh-release@v0.1.15
        with:
          files: checksums.txt
