name: 'Build NSO-RPC - x86_64'
on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build NSO-RPC - x86_64'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10.11

    # Windows Build
    - name: "Build"
      if: matrix.os == 'windows-latest'
      run: |
        cd scripts && 
        python -m pip install pyqt6 &&
        ./build.bat

    - name: "Upload Build"
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: client/dist/NSO-RPC.exe

    # Linux Build
    - name: "Upload script"
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: scripts/linux.sh

    # MacOS Build
    - name: "Build"
      if: matrix.os == 'macos-latest'
      run: |
        cd scripts &&
        python -m pip install pyqt6 &&
        bash ./build.sh &&
        cd ../client/dist &&
        ln -s /Applications "Applications (admin)" &&
        hdiutil create -fs HFS+ -srcfolder . -volname NSO-RPC mac-installer.dmg &&
        zip -yr mac-portable.zip NSO-RPC.app/

    - name: "Upload Build"
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/mac-installer.dmg
          client/dist/mac-portable.zip

  get-hashes:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - name: "Generate checksums.txt"
        uses: MCJack123/ghaction-generate-release-hashes@v4
        with:
          hash-type: sha256
          file-name: checksums.txt
          get-assets: true
      - uses: softprops/action-gh-release@v0.1.15
        with:
          files: checksums.txt