name: 'Build NSO-RPC - Universal2'
on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build NSO-RPC'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    # MacOS Build
    - name: "Build Universal2"
      run: |
        curl https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg -o python-3.10.11-macos11.pkg
        sudo installer -verbose -pkg python-3.10.11-macos11.pkg -target / &&
        python3.10 -m pip install PyQt6 &&
        cd scripts/macos-universal2 &&
        ./build.sh &&
        python3 debloat-qt.py &&
        cd ../../client/dist &&
        ln -s /Applications "Applications (admin)" &&
        hdiutil create -fs HFS+ -srcfolder . -volname NSO-RPC mac-universal2-installer.dmg &&
        zip -yr mac-universal2-portable.zip NSO-RPC.app/

    - name: "Upload Universal2 Build"
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          client/dist/mac-universal2-installer.dmg
          client/dist/mac-universal2-portable.zip
